name: Continuous Integration
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: HannesWell/eclipse.platform.releng.aggregator/.github/workflows/mavenBuild.yml@mavenBuild-win-cmd
